name-template: "Draft"
tag-template: "draft"
categories:
  - title: "⬆️ Dependencies"
    collapse-after: 3
    labels:
      - "dependencies"

  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"

  - title: "🚀 Features"
    labels:
      - "feature"

  - title: "📄 Documentation"
    labels:
      - "documentation"

  - title: "🧰 Maintenance"
    labels:
      - "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES

  **Full changelog**: [`$PREVIOUS_TAG...$RESOLVED_VERSION`](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
